using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using BirdCafe.Shared;
using BirdCafe.Shared.ViewModels;
using BirdCafe.UI.Components;
using System.Linq;

namespace BirdCafe.UI.Gameplay.Day
{
    /// <summary>
    /// Manages the playback of the daily simulation.
    /// It translates the data-driven timeline from the Engine into Unity animations, UI updates, and bubbles.
    /// </summary>
    public class SimulationVisualizer : MonoBehaviour
    {
        [Header("References")]
        [Tooltip("The UI widget displaying the time of day and progress slider.")]
        public DayProgressUI dayProgress;

        [Tooltip("The counter for money/profit.")]
        public StatCounterUI moneyCounter;

        [Tooltip("The counter for cafe popularity.")]
        public StatCounterUI popularityCounter;

        [Header("Actors")]
        [Tooltip("The transform where bubbles spawn (e.g. the bird's head).")]
        public RectTransform birdAnchor;

        [Tooltip("Prefab for the thought bubble appearing above birds.")]
        public GameObject thoughtBubblePrefab;

        [Header("Settings")]
        [Tooltip("Total duration of the simulation in seconds. Must match the Engine config.")]
        public float dayDuration = BirdCafeGame.Instance.Controller.CurrentState.Config.DayDurationSeconds;

        [Tooltip("Speed multiplier for playback. 1.0 = realtime, 2.0 = 2x speed.")]
        public float timeScale = 1.5f;

        [Tooltip("Maximum number of timeline events to process per frame to prevent freezing.")]
        public int maxEventsPerFrame = 10;

        // Internal State

        /// <summary>
        /// Current playback time in seconds.
        /// </summary>
        private float _currentTimer;

        /// <summary>
        /// The list of events generated by the simulation engine.
        /// </summary>
        private List<UiTimelineEvent> _timeline;

        /// <summary>
        /// Tracks which event in the timeline we are currently waiting for.
        /// </summary>
        private int _eventIndex;

        // Tracking running totals for animation
        private float _currentMoney;
        private float _currentPopularity;

        // Dictionary to store fun sayings
        private Dictionary<string, List<string>> _sayings;

        private void Awake()
        {
            InitializeSayings();
        }

        private void InitializeSayings()
        {
            _sayings = new Dictionary<string, List<string>>
            {
                {
                    "Coffee", new List<string>
                    {
                        "Order up - one coffee!",
                        "I’ve got a cappuccino here.",
                        "Coffee’s ready for pickup!"
                    }
                },
                {
                    "BakedGoods", new List<string>
                    {
                        "Fresh croissant served!",
                        "One pastry, coming up!",
                        "Hot muffin, order up!"
                    }
                },
                {
                    "ThemedMerch", new List<string>
                    {
                        "Enjoy the new mug!",
                        "One T-shirt, sold!",
                        "Nice choice of merch!"
                    }
                },
                {
                    "Angry", new List<string>
                    {
                        "Can't please everyone.",
                        "They looked grumpy.",
                        "Oof, they walked out."
                    }
                }
            };
        }

        /// <summary>
        /// Called when the object becomes active. Initializes the simulation replay.
        /// </summary>
        private void OnEnable()
        {
            // Reset local timers and indices.
            _currentTimer = 0f;
            _eventIndex = 0;

            // Retrieve initial data snapshots from the Engine.
            var intro = BirdCafeGame.Instance.GetDayIntro();
            var care = BirdCafeGame.Instance.GetCareDashboard(); // Using care dashboard to get current money snapshot.

            // initialize local tracking variables.
            _currentMoney = care != null ? (float)care.CurrentMoney : 0f;
            _currentPopularity = intro != null ? intro.Popularity : 0f;

            // Retrieve the full list of events that happened during the simulation.
            _timeline = BirdCafeGame.Instance.GetDayTimeline();

            // Rewind the money and popularity state to the beginning of the day.
            // We subtract all money and popularity gained/lost in the timeline from the current total to find the starting point.
            if (_timeline != null && _timeline.Count > 0)
            {
                var deltaMoney = _timeline.Sum(x => x.MoneyDelta);
                _currentMoney -= (float)deltaMoney;

                var deltaPop = _timeline.Sum(x => x.PopularityDelta);
                _currentPopularity -= deltaPop;
            }

            // Initialize the UI elements with starting values.
            if (moneyCounter) moneyCounter.Value = _currentMoney;
            if (popularityCounter) popularityCounter.Value = _currentPopularity;

            // Pass 0 seconds to initialize the clock at start time (e.g., 7:00 AM).
            if (dayProgress) dayProgress.UpdateVisuals(0f);

            // Force layout rebuild immediately to prevent UI widgets from stacking 
            Canvas.ForceUpdateCanvases();

            dayDuration = BirdCafeGame.Instance.Controller.CurrentState.Config.DayDurationSeconds;

            // Begin the playback loop.
            StartCoroutine(RunSimulationRoutine());
        }

        /// <summary>
        /// Called when the object is disabled or destroyed.
        /// </summary>
        private void OnDisable()
        {
            // Critical: Ensure coroutines stop if the panel is disabled mid-simulation.
            StopAllCoroutines();
        }

        /// <summary>
        /// Called by GameplayUI when the Skip button is pressed.
        /// Instantly calculates remaining events and finishes the day.
        /// </summary>
        public void SkipSimulation()
        {
            // Stop the playback coroutine immediately.
            StopAllCoroutines();

            // Iterate through all remaining events in the timeline to apply their mathematical effects.
            if (_timeline != null)
            {
                while (_eventIndex < _timeline.Count)
                {
                    var evt = _timeline[_eventIndex];
                    _currentMoney += (float)evt.MoneyDelta;
                    _currentPopularity += evt.PopularityDelta;
                    _eventIndex++;
                }
            }

            // Snap UI elements to their final values without animation.
            if (moneyCounter) moneyCounter.Value = _currentMoney;
            if (popularityCounter) popularityCounter.Value = _currentPopularity;

            // Pass total duration (seconds) instead of normalized 1.0f.
            if (dayProgress) dayProgress.UpdateVisuals(dayDuration);

            // Notify the Engine that visualization is complete.
            BirdCafeGame.Instance.FinishSimulation();
        }

        /// <summary>
        /// Coroutine that runs every frame to advance the simulation timer and trigger events.
        /// </summary>
        private IEnumerator RunSimulationRoutine()
        {
            // Continue loop until the timer exceeds the defined day duration.
            while (_currentTimer < dayDuration)
            {
                // Advance timer based on delta time and speed multiplier.
                _currentTimer += Time.deltaTime * timeScale;

                // Pass raw seconds to UpdateVisuals.
                if (dayProgress) dayProgress.UpdateVisuals(_currentTimer);

                // Check for and fire any events that occurred up to this point in time.
                ProcessEvents();

                yield return null;
            }

            // Ensure the UI shows exactly the end time (e.g. 3:00 PM / 100%) when finished.
            if (dayProgress) dayProgress.UpdateVisuals(dayDuration);

            // Pause briefly to let the user see the final state before closing.
            yield return new WaitForSeconds(1.0f);

            // Notify the Engine that visualization is complete.
            BirdCafeGame.Instance.FinishSimulation();
        }

        /// <summary>
        /// Checks the timeline against the current timer and fires events that are due.
        /// </summary>
        private void ProcessEvents()
        {
            if (_timeline == null) return;

            int eventsProcessedThisFrame = 0;

            // Loop through the timeline starting from the last processed index.
            // Continue as long as there are events left AND the event's timestamp is less than or equal to current time.
            while (_eventIndex < _timeline.Count &&
                   _timeline[_eventIndex].TimeSeconds <= _currentTimer)
            {
                var evt = _timeline[_eventIndex];
                PlayEvent(evt);
                _eventIndex++;

                // Performance Safety: Break out if we process too many events in a single frame (e.g. lag spike catch-up).
                // This prevents the game from freezing if 1000 events happen simultaneously.
                eventsProcessedThisFrame++;
                if (eventsProcessedThisFrame >= maxEventsPerFrame)
                {
                    break;
                }
            }
        }

        /// <summary>
        /// Executes the logic for a single specific timeline event.
        /// </summary>
        /// <param name="evt">The event data.</param>
        private void PlayEvent(UiTimelineEvent evt)
        {
            // 1. Apply Financial and Popularity changes to the running totals.
            if (evt.MoneyDelta != 0)
            {
                _currentMoney += (float)evt.MoneyDelta;
                // Trigger the rolling number animation on the UI.
                if (moneyCounter) moneyCounter.AnimateValue(_currentMoney, 0.5f);
            }

            if (evt.PopularityDelta != 0)
            {
                _currentPopularity += evt.PopularityDelta;
                if (popularityCounter) popularityCounter.AnimateValue(_currentPopularity, 0.5f);
            }

            // 2. Trigger visual feedback (Bubbles) for specific interesting events.
            if (evt.EventType == "ServiceCompleted")
            {
                // IconId matches our Dictionary keys ("Coffee", "BakedGoods", etc.)
                string msg = GetFunSaying(evt.IconId);
                SpawnBubble(msg);
            }
            else if (evt.EventType == "ServiceFailed" || evt.EventType == "LeftUnhappy")
            {
                string msg = GetFunSaying("Angry");
                SpawnBubble(msg);
            }
        }

        /// <summary>
        /// Returns a randomized short saying from the dictionary.
        /// </summary>
        private string GetFunSaying(string categoryId)
        {
            if (_sayings != null && _sayings.ContainsKey(categoryId))
            {
                var list = _sayings[categoryId];
                if (list != null && list.Count > 0)
                {
                    return list[Random.Range(0, list.Count)];
                }
            }

            // Fallback for unexpected categories or empty lists
            return $"Sold {categoryId}!";
        }

        /// <summary>
        /// Instantiates a thought bubble prefab above the bird anchor.
        /// </summary>
        /// <param name="text">Text to display inside the bubble.</param>
        private void SpawnBubble(string text)
        {
            if (thoughtBubblePrefab && birdAnchor)
            {
                // Create the bubble as a child of the anchor point.
                var go = Instantiate(thoughtBubblePrefab, birdAnchor);

                // Reset transform to ensure it appears at the anchor's position.
                var rect = go.GetComponent<RectTransform>();

                // Add a tiny random offset so bubbles don't stack perfectly if 2 happen at once
                float rX = Random.Range(-80f, 80f);
                float rY = Random.Range(-10f, 10f);
                rect.anchoredPosition = new Vector2(rX, rY);

                rect.localScale = Vector3.one;

                // Set the text content.
                var script = go.GetComponent<ThoughtBubble>();
                if (script) script.Initialize(text);
            }
        }
    }
}